パッケージ構成を Lerna 標準構成に準拠させる
lerna-stack/lerna-handson pull request #27
Opened 2021-04-21 06:08 UTC by xirc

## 内容
Lerna 標準のパッケージ構成に従うように、パッケージ構成を整理しました。
- [x] パッケージ&一部クラスのリネーム (main/**)
- [x] パッケージ&一部クラスのリネーム (test/**)
- [x] README 更新
    - [x] パッケージ構成の更新

## 動作確認項目
- [x] sbt コマンド動作確認
  - [x] 演習未実装時にはテストに失敗すること
  - [x] 演習実装後にはテストに成功すること
  コマンド一覧
    - [x] `sbt testMyConcertActorBinding`
    - [x] `sbt testMyConcertActor`
    - [x] `sbt testMyBoxOfficeServiceBinding`
    - [x] `sbt testMyBoxOfficeService`
    - [x] `sbt testMyBoxOfficeResourceBinding`
    - [x] `sbt testMyBoxOfficeResource`
    - [x] `sbt testMyConcertProjectionRepositoryBinding`
    - [x] `sbt testMyConcertProjectionRepository`
- [x] 結合動作確認
    - [x] サーバを2台起動し、curlコマンド5種類が意図通りに動作しているか
- [x] パッケージごとの依存関係が標準構成に従っているか
  パッケージをサブプロジェクトにすることまでは実施していません。
  ハンズオンとしてはそこまでする必要ないと考えています。
  パッケージごとの依存関係を IntelliJ IDEA の Dependency Structure Matrix で確認しました。  
  [Dependency Structure Matrix | IntelliJ IDEA](https://www.jetbrains.com/help/idea/dsm-analysis.html)

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/application/http/MainHttpApiServerDiDesign.scala
> -}
内容は分割して、別のクラスに移動しました。

- `MainHttpApiServerConfig` => `MainDIDesign` に配置します。
- `ResourceExecutionContext` => 削除 (ApplicationExecutionContextに統合しました)
- `MainHttpApiServerResource`  => `BoxOfficeResource` にリネームし、`PresentationDIDesign` に配置します

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/application/http/package.scala
> -}
`ApplicationExecutionContext` に統合したため、`ResourceExecutionContext` は削除されます。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/application/projection/DefaultConcertProjection.scala
> +) extends ConcertProjection {
`ConcertProjection` trait を `adapter` パッケージに追加し、`DefaultConcertProjection` はその trait を実装します。
`Main` からは `DefaultConcertProjection` を直接参照しないようにしました。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/model/ModelDiDesign.scala
> -}
内容を `ApplicationDIDesign` に移動しました。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/presentation/BoxOfficeResource.scala
> +trait BoxOfficeResource {
`DefaultBoxOfficeResource` と `MyBoxOfficeResource` が実装クラスになるため、それらに合わせて名前を変更しました。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/presentation/GlobalExceptionHandler.scala
> +object GlobalExceptionHandler {
`My***` を実装しないクラスについては、可能な限り `Default` を外すようにしました。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/readmodel/ConcertRepository.scala
> -}
`adapter` パッケージに移動しました。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/readmodel/ConcertItem.scala
> -case class ConcertItem(id: ConcertId, numberOfTickets: Int, cancelled: Boolean)
ConcertRepository のコンパニオンオブジェクトの中に 移動しました。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/readmodel/DefaultReadModelDiDesign.scala
> -}
一部のDI定義は `ApplicationDIDesign` に移動しました。
- `RepositoryExecutionContext` => `ApplicationExecutionContext` に統合しました
- `ConcertRepository` => `ApplicationDIDesign` に移動しました
- `ConcertProjectionRepository` =>  `ApplicationDIDesign` に移動しました

残り(`ConcertDatabaseService`, `DefaultConcertDatabaseServiceConfig`) は、`ReadModelDIDesign` に配置しています。

2021-04-21 06:34 UTC, xirc commented on sample-app/src/main/scala/example/presentation/protocol/BuyConcertTicketsRequestBody.scala
> +package example.presentation.protocol
`example.presentation.protocol` に HTTP エンドポイントで使用するクラスがあります。

[lerna-sample-payment-app/プロジェクト構成詳解.md at main · lerna-stack/lerna-sample-payment-app](https://github.com/lerna-stack/lerna-sample-payment-app/blob/main/docs/%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%A7%8B%E6%88%90%E8%A9%B3%E8%A7%A3.md#%E3%83%97%E3%83%AD%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E6%A7%8B%E6%88%90%E8%A9%B3%E8%A7%A3)
これらのクラスが `DTO` に該当するのであれば、 `adapter` に配置するのが良さそうでしょうか？  
Lerna 標準のパッケージ構造に不慣れなため、どこに配置するのが良いのか教えて頂けると助かります。
`presentation` 以外で使わないように考えたため、今のところはそのまま `presentation` の中に配置しています。

2021-04-21 06:39 UTC, xirc commented
当初は `Akka Typed` 対応のみを予定していましたが、それ以外の変更も含めて次のリリースに入れるようになったため、PRのターゲットブランチを `feature/develop` などスコープが広いことが分かる名前のものを使用したほうが良いかもしれません。

そのほうが良さそうであれば、現時点の `feature/akka-typed` ブランチから `feature/develop` ブランチを作成しようかと思います。どのように思いますか？

2021-04-22 02:41 UTC, tksugimoto commented
@xirc 
> 当初は `Akka Typed` 対応のみを予定していましたが、それ以外の変更も含めて次のリリースに入れるようになったため、PRのターゲットブランチを `feature/develop` などスコープが広いことが分かる名前のものを使用したほうが良いかもしれません。
> 
> そのほうが良さそうであれば、現時点の `feature/akka-typed` ブランチから `feature/develop` ブランチを作成しようかと思います。どのように思いますか？

はい、ブランチ名を変えたほうが良いと思います。

2021-04-22 03:43 UTC, xirc commented
@tksugimoto 

`feature/akka-typed` から `feature/develop` を作成しました。
この PR のターゲットブランチを `feature/develop` に変更しました。

2021-04-22 04:44 UTC, tksugimoto requested changes

2021-04-22 05:52 UTC, xirc commented on README.md
> +[プロジェクト構成詳解](https://github.com/lerna-stack/lerna-sample-payment-app/blob/65469a3cec9c8fcba3deeb6ccd6fc13a51ad29a5/docs/プロジェクト構成詳解.md) と同様の構成になっています。
ありがとうございます。対応しました。  
> Revise URL to be human-readable 2a6b1b3

2021-04-22 05:53 UTC, xirc commented on README.md
> +- `readmodel`
ありがとうございます。対応しました。
> Write package descriptions in a consistent way 9f3ba01

2021-04-22 06:06 UTC, xirc commented on sample-app/src/main/scala/example/adapter/ConcertProjectionRepository.scala
> +package example.adapter
ありがとうございます。対応しました。
> Move ConcertProjectionRepository into example.application.projection … … 7510c5a
> Move ConcertEvent into example.application package d5c2439
> Move KryoSerialization into example.application package bdfd89e

この変更による影響を受けるであろう部分を動作確認してあります。
* [x] `ApplicationDIDesign` の `MyConcertProjectionRepository` を有効にし、 `sbt testMyConcertProjectionRepositoryBinding` にパスすること
   ```
          // MyConcertProjectionRepository実装時にコメントアウトを外す (この行はそのまま)
          // .bind[ConcertProjectionRepository].to[MyConcertProjectionRepository]
  ```
* [x] `MyConcertActor` を実装し、`sbt testMyConcertActor` にパスすること
* [x] `MyConcertProjectionRepository` を実装し、`sbt testMyConcertProjectionRepository` にパスすること

2021-04-22 06:06 UTC, tksugimoto commented on README.md
> +- `readmodel`
application の子の package ではなく、兄弟のpackageについての指摘でした。

`application.command` などはどちらでも良いと思います。

2021-04-22 06:06 UTC, xirc commented on sample-app/src/main/scala/example/presentation/package.scala
> +  type PresentationExecutionContext = ExecutionContext
ありがとうございます。変更しました。
> Update comments at presentation package object 4bccfb2

2021-04-22 06:07 UTC, xirc commented on sample-app/src/test/scala/example/presentation/MyBoxOfficeResourceBindSpec.scala
> +    val resource = session.build[BoxOfficeResource]
ありがとうございます。似たような箇所も合わせて変更しました。

> Revise comments and testcase names of some BindSpecs 0836a74

2021-04-22 06:18 UTC, tksugimoto commented on sample-app/src/main/scala/example/application/ApplicationDIDesign.scala
> +import example.adapter.{ BoxOfficeService, ConcertProjection, ConcertRepository }
> example.adapter.{ BoxOfficeService, ConcertProjection, ConcertRepository }

adapter 側も application と同じように サブパッケージ `command`, `projection`, `query` などを作って、その下においたほうが良いと思います。

2021-04-22 06:47 UTC, xirc commented on README.md
> +- `readmodel`
失礼しました。見るところ間違っていました。
コメントを頂いた内容に対応しました。
> Write package descriptions in a consistent way 42c5e66

2021-04-22 06:49 UTC, xirc commented on sample-app/src/main/scala/example/application/ApplicationDIDesign.scala
> +import example.adapter.{ BoxOfficeService, ConcertProjection, ConcertRepository }
ありがとうございます。
3つのクラス(`BoxOfficeService`, `ConcertProjection`, `ConcertRepository`) を対応するパッケージに移動しました。
> Move BoxOfficeServe into example.adapter.command package e834e2f
> Move ConcertRepository into example.adapter.query package 12d70f4
> Move ConcertProjection into example.adapter.projection package b5b5a22

2021-04-22 07:00 UTC, tksugimoto approved these changes

2021-04-22 07:00 UTC, merged