ハンズオン「Scala言語の基礎」内容の改善
lerna-stack/lerna-handson pull request #34
Opened 2021-05-14 09:05 UTC by xirc

2021-05-14 09:18 UTC, xirc commented on exercise-scala-basic/src/main/scala/example/VectorExample.scala
> +  val myVector2                  = Vector(4, 5, 6)
myVector2(0) = 1
とすると、0-indexed なのか、1-indexed なのか混乱を生みそうだったため、値を変更しました。

2021-05-14 09:18 UTC, xirc commented on exercise-scala-basic/src/main/scala/exercise/Exercise5A.scala
> +  }
`converted.foreach(println)` と書くことができますが、
初学者の分かりやすさのために、このように記述してあります。

2021-05-14 09:18 UTC, xirc commented on exercise-scala-basic/src/main/scala/exercise/Exercise5B.scala
> +  converted.foreach(println)
2回目の `foreach` の登場なので、簡潔なスタイルで書いてみました。
ここでも
```scala
  converted.foreach { x: Double =>
    println(x)
  }
```
と書いたほうが良さそうでしょうか？

2021-05-15 23:56 UTC, tksugimoto requested changes

2021-05-15 23:56 UTC, tksugimoto commented on exercise-scala-basic/src/main/scala/example/ObjectApplyExample.scala
> +  println(number4) // 4
[IMO]

```
  val number4: Int = SquaredIntFactory(2)
  println(number4) // 4
```

変数名の `4` は不要だと思いました。

- number1, 2, 3 があるわけではない
- 値が `4` なので紛らわしい

2021-05-15 23:56 UTC, tksugimoto commented on exercise-scala-basic/src/main/scala/example/VectorExample.scala
> +  println(myVector2(1)) // 6
[MUST]

>   println(myVector2(1)) // 6

`6` ではなく、 `5` ではないでしょうか？

```scala
  val myVector2                  = Vector(4, 5, 6)
```

2021-05-15 23:57 UTC, tksugimoto commented on exercise-scala-basic/src/main/scala/exercise/Exercise5B.scala
> +  converted.foreach(println)
簡潔なスタイルで良いと思います。

2021-05-16 00:51 UTC, tksugimoto commented on exercise-scala-basic/src/main/scala/answer/Answer2A.scala
>  object Answer2A extends App {
テキストだと、 `Exercise2.scala` ですが、実際は、 `Exercise2A.scala`, `Exercise2B.scala` に分かれています。
````
[演習2] match式
• ファイルの場所
– exercise-scala-basic/src/main/scala/exercise/Exercise2.scala
– 解答 exercise-scala-basic/src/main/scala/answer/Answer2.scala
```

他にも同様のものが多いならば、別MRでの対応でもOKです。

2021-05-16 01:01 UTC, xirc commented on exercise-scala-basic/src/main/scala/answer/Answer2A.scala
>  object Answer2A extends App {
記載ミスだと思われます。
「Scala言語の基礎」にある他の演習も同様のものがあれば、本PR で対応致します。

2021-05-16 01:07 UTC, tksugimoto commented on exercise-scala-basic/src/main/scala/answer/Answer2A.scala
>  object Answer2A extends App {
演習5 は `5A` となっていました。しかし、 `5B` は記載なし

```
[演習5] Vectorを使ってみよう
• ファイルの場所
– exercise-scala-basic/src/main/scala/exercise/Exercise5A.scala
– 解答 exercise-scala-basic/src/main/scala/answer/Answer5A.scala

``

2021-05-16 01:19 UTC, xirc commented on exercise-scala-basic/src/main/scala/answer/Answer2A.scala
>  object Answer2A extends App {
ありがとうございます。
コメントを頂いた箇所以外はなさそうでした。
更新対象ページは、p28, p50 です。

対応しました。
> Update 「Scala言語の基礎」 … 9b7dca9

2021-05-16 01:20 UTC, xirc commented on exercise-scala-basic/src/main/scala/example/VectorExample.scala
> +  println(myVector2(1)) // 6
ありがとうございます。
サンプルコード、スライドを更新しました。

> Make comment intended d37ad2d
> Update 「Scala言語の基礎」 … 9b7dca9

2021-05-16 01:24 UTC, tksugimoto approved these changes

2021-05-16 01:24 UTC, merged